ManagerLogbook/ManagerLogbook.Web/Controllers/LogbooksController.cs
using ManagerLogbook.Services.Bll.Contracts;
using ManagerLogbook.Services.Contracts;
using ManagerLogbook.Services.Contracts.Providers;
using ManagerLogbook.Web.Mappers;
using ManagerLogbook.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerLogbook.Web.Controllers
{
    [Authorize(Roles = "Admin,Manager")]
    public class LogbooksController : Controller
    {
        private readonly ILogbookService logbookService;
        private readonly IUserService userService;
        private readonly INoteEngine _noteEngine;
        private readonly IUserServiceWrapper wrapper;

        public LogbooksController(ILogbookService logbookService,
                                  IUserService userService,
                                  INoteEngine noteEngine,
                                  IUserServiceWrapper wrapper)
        {
            this.logbookService = logbookService;
            this.userService = userService;
            _noteEngine = noteEngine;
            this.wrapper = wrapper;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var logbook = await this.logbookService.GetLogbookDetailsAsync(id);
            var managers = await this.userService.GetAllManagersPresentInLogbookAsync(logbook.Id);

            var viewModel = new IndexLogbookViewModel
            {
                Logbook = logbook.MapFrom(),
                AssignedManagers = managers.Select(x => x.MapFrom()).ToList()
            };

            var userId = this.wrapper.GetLoggedUserId(User);
            if (User.IsInRole("Manager"))
            {
                viewModel.ActiveNotes = (await _noteEngine.ShowLogbookNotesWithActiveStatusAsync(userId, logbook.Id)).Select(x => x.MapFrom()).ToList();
                viewModel.TotalNotes = (await _noteEngine.ShowLogbookNotesAsync(userId, logbook.Id)).Select(x => x.MapFrom()).ToList();
            }

            return View(viewModel);
        }
    }
}

ManagerLogbook/ManagerLogbook.Web/Controllers/ReviewsController.cs
using ManagerLogbook.Services.Contracts;
using ManagerLogbook.Web.Mappers;
using ManagerLogbook.Web.Models;
using ManagerLogbook.Web.Utils;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ManagerLogbook.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewService reviewService;

        public ReviewsController(IReviewService reviewService)
        {
            this.reviewService = reviewService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReviewViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(WebConstants.EnterValidData);
            }

            var model = viewModel.MapFrom();

            var review = await this.reviewService.CreateReviewAsync(model);

            if (review.OriginalDescription == viewModel.OriginalDescription)
            {
                return Ok(string.Format(WebConstants.ReviewCreated));
            }

            return BadRequest(string.Format(WebConstants.ReviewNotCreated));
        }
    }
}

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_AddManagerModalPartial.cshtml
@model LogbookViewModel
<!-- Add Manager To Logbook Modal -->
<div class="modal fade" id="myModalAddManager" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Choose manager to add in logbook</h4>
            </div>
            <div class="modal-body">
                <div asp-validation-summary="All" class="text-danger-custom"></div>
                <form id="submit-form-add-manager" asp-area="Admin" asp-controller="Logbooks" asp-action="AddManagerToLogbook" method="post" class="loginForm">
                    <select id="manager-selector" class="form-control" asp-for="ManagerId"></select>
                    <input type="hidden" id="logbook-id" value="@Model.Id">
                    @*<input type="hidden" name="Id" value="@Model.Id">*@
                    <div class="margin-5">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Add Manager To Logbook Modal -->

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_AddModeratorModalPartial.cshtml
@model BusinessUnitViewModel
<!-- Add Moderator To Business Unit Modal -->
<div class="modal fade" id="myModalAddModerator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Choose moderator to add to business unit</h4>
            </div>
            <div class="modal-body">
                <div asp-validation-summary="All" class="text-danger-custom"></div>
                <form id="submit-form-add-moderator" asp-area="Admin" asp-controller="BusinessUnits" asp-action="AddModeratorToBusinessUnit" method="post" class="loginForm">
                    <input type="hidden" id="my-add-moderator-value" value="@Model.Id">
                    <select id="moderator-selector" class="form-control" asp-for="ModeratorId"></select>
                    <div class="margin-5">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Add Moderator To Business Unit Modal -->

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_BusinessUnitsPartial.cshtml
@model BusinessUnitSearchViewModel

@{
    ViewData["Title"] = "_BusinessUnitPartial";
}

<!-- CATEGORY LIST SECTION -->
<section class="clerfix" style="padding-top:0%; padding-bottom:0%">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                @if (Model.BusinessUnits != null)
                {
                    <div class="resultBar barSpaceAdjust">
                        <h2>We found <span>@Model.BusinessUnits.Count()</span> Results for you</h2>
                    </div>
                }
                else
                {
                    <div class="resultBar barSpaceAdjust">
                        <h2>We found <span>0</span> Results for you</h2>
                    </div>
                }

                @foreach (var businessUnit in Model.BusinessUnits)
                {
                    <div class="listContent">
                        <div class="row">
                            <div class="col-sm-5 col-xs-12">
                                <div class="categoryImage">
                                    <a href="/BusinessUnits/Details/@businessUnit.Id"><img src="~/images/@(businessUnit.Picture ?? "noimage.jpg")" href= alt="Image category" class="img-responsive img-rounded"></a>
                                </div>
                            </div>
                            <div class="col-sm-7 col-xs-12">
                                <div class="categoryDetails">
                                    <h2><a href="/BusinessUnits/Details/@businessUnit.Id" style="color: #222222">@businessUnit.Name </a><span class="likeCount"><i class="fa fa-heart-o" aria-hidden="true"></i> @businessUnit.Likes</span></h2>
                                    <p>@businessUnit.Address <span class="placeName">@businessUnit.TownName </span></p>
                                    <p>@businessUnit.Information </p>
                                    <ul class="list-inline list-tag">
                                        <li>@businessUnit.CategoryName</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_CreateAccountModalPartial.cshtml
@model RegisterViewModel

<!-- Create Account Modal -->
<div class="modal fade" id="myModalRegister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create new account</h4>
            </div>
            <div class="modal-body">
                <div class="text-danger-custom"></div>
                <form id="submit-form-account" asp-area="Admin" asp-controller="Create" asp-action="Register" method="post" class="loginForm">
                    <div class="form-group">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <input asp-for="UserName" class="form-control" placeholder="Username">
                        <span asp-validation-for="UserName" class="text-danger-custom"></span>

                    </div>
                    <div class="form-group">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <input asp-for="Email" type="email" class="form-control" id="email" placeholder="Email">
                        <span asp-validation-for="Email" class="text-danger-custom"></span>
                    </div>
                    <div class="form-group">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                        <input asp-for="Password" type="password" class="form-control" id="pwd" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                        <input asp-for="ConfirmPassword" type="password" class="form-control" placeholder="Password">
                        <span asp-validation-for="ConfirmPassword" class="text-danger-custom"></span>
                    </div>
                    <div class="padding-bottom-8">
                        <div class="contactSelect">
                            <select asp-for="UserRole" class="form-control">
                                <option value="Moderator">Moderator</option>
                                <option value="Manager">Manager</option>
                                <option value="Admin">Admin</option>
                            </select>
                        </div>
                    </div>
                    <div class="text-centered">
                        <img id="ImgPreview-create-account" class="preview1" src="" />
                        <input type="button" id="removeImage1-create-account" value="x" class="btn-rmv1" />
                    </div>
                    <label name="Image" class="btn btn-primary-custom browse margin-5">Upload Image</label>
                    <input type="file" id="imag-create-account" name="UserImage" class="btn btn-primary file" accept="image/*">
                    <div class="margin-5">
                        <button type="submit" asp-area="Admin" asp-controller="Create" asp-action="Register" class="btn btn-primary btn-block">Create Account</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Create Account Modal -->

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_CreateLogbookModalPartial.cshtml
@model LogbookViewModel
<!--  Start Modal Create Logbook-->
<div class="modal fade" id="myModalCreateLogbook" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create a logbook</h4>
            </div>
            <div class="modal-body">
                <div class="text-danger-custom"></div>
                <form id="create-logbook" asp-area="Admin" asp-controller="Logbooks" asp-action="Create" enctype="multipart/form-data" method="post" class="loginForm">
                    <div class="form-group">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <input asp-for="Name" class="form-control" id="name" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger-custom"></span>
                    </div>
                    <select id="business-unit-create-selector" class="form-control" asp-for="BusinessUnitId"></select>

                    <div class="text-centered">
                        <img id="ImgPreview-create-logbook" class="preview1" src="" />
                        <input type="button" id="removeImage1-create-logbook" value="x" class="btn-rmv1" />
                    </div>
                    <label name="Picture" class="btn btn-primary-custom browse margin-5">Upload Image</label>
                    <input type="file" id="imag-create-logbook" name="LogbookPicture" class="btn btn-primary file" accept="image/*">

                    <div class="margin-5">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Update Logbook Modal -->

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_FooterPartial.cshtml
@model HomeViewModel

<section class="clearfix countUpSection">
    <div class="container text-block-center">
        <div class="row">
            <div class="col-sm-3 col-xs-12">
                <div class="text-center countItem">
                    <div class="counter">@Model.Towns.Count()</div>
                    <div class="counterInfo bg-color-1">Cities</div>
                </div>
            </div>
            @foreach (var category in Model.Footer.BusinessUnitsCategories)
            {
                <div class="col-sm-3 col-xs-12">
                    <div class="text-center countItem">
                        <div class="counter">@category.Value</div>
                        <div class="counterInfo bg-color-3">@category.Key</div>
                    </div>
                </div>
            }
          
        </div>
    </div>
</section>

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Template color -->
    <link rel="stylesheet" href="~/assets/css/default.css" id="option_color">

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- PLUGINS CSS STYLE -->
    <link href="/assets/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet">
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/plugins/listtyicons/style.css" rel="stylesheet">
    <link href="/assets/plugins/bootstrapthumbnail/bootstrap-thumbnail.css" rel="stylesheet">
    <link href="/assets/plugins/datepicker/datepicker.min.css" rel="stylesheet">
    <link href="/assets/plugins/selectbox/select_option1.css" rel="stylesheet">
    <link href="/assets/plugins/owl-carousel/owl.carousel.min.css" rel="stylesheet">
    <link href="/assets/plugins/fancybox/jquery.fancybox.min.css" rel="stylesheet" />
    <link href="/assets/plugins/isotope/isotope.min.css" rel="stylesheet">
    <link href="/assets/plugins/map/css/map.css" rel="stylesheet">
    <link href="/assets/plugins/rateyo/jquery.rateyo.min.css" rel="stylesheet">
    <link href="/assets/plugins/animate/animate.css" rel="stylesheet">
    <link href="" rel="stylesheet" id="bootstrap-rtl">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

    <!-- GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">
    @*<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    <!-- CUSTOM CSS -->
    <link href="/assets/css/app.css" rel="stylesheet">
    <link href="~/assets/css/custom.css" rel="stylesheet">

    <!-- MAGNIFIC POP UP CSS -->
    <link href="~/assets/css/magnific-popup.css" rel="stylesheet">

    <link rel="stylesheet" href="/assets/css/default.css" id="option_color">

    <!-- FAVICON -->
    <link href="/assets/img/favicon.png" rel="shortcut icon">

    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManagerLogbook</title>

</head>
<body id="body" class="body-wrapper boxed-menu">
    <!-- <div class="page-loader" style="background: url(img/preloader.gif) center no-repeat #fff;"></div> -->
    <!-- Preloader -->
    <div id="preloader" class="smooth-loader-wrapper">
        <div class="smooth-loader">
            <div class="loader1">
                <div class="loader-target">
                    <div class="loader-target-main"></div>
                    <div class="loader-target-inner"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-wrapper">
        <!-- HEADER -->
        <header id="pageTop" class="header">

            <!-- TOP INFO BAR -->

            <div class="nav-wrapper navbarWhite">
                <!-- NAVBAR -->
                <nav id="menuBar" class="navbar navbar-default transparent-navbar " role="navigation">
                    <div class="container">

                        @*<nav id="menuBar" class="navbar navbar-default lightHeader animated " role="navigation">
                            <div class="container">*@

                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse navbar-ex1-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li class=""><a asp-controller="Home" asp-action="Index">Home</a></li>
                                <li class=" dropdown singleDrop">
                                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Panel<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                    <ul class="dropdown-menu">
                                        <li class=""> @await Html.PartialAsync("_LoginPartial") </li>
                                    </ul>
                                </li>
                                @if (User.IsInRole("Manager"))
                                {
                                    <li class=""><a asp-area="Manager" asp-controller="Notes" asp-action="Index">Dashboard</a></li>
                                }
                                @if (User.IsInRole("Moderator"))
                                {
                                    <li class=""><a asp-area="Moderator" asp-controller="Reviews" asp-action="Index">Dashboard</a></li>
                                }
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class=" dropdown singleDrop">
                                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                        <ul class="dropdown-menu">
                                            <li><a data-toggle="modal" data-target="#myModalRegister" class="padding-bottom-0">Account</a></li>
                                            <li><a data-toggle="modal" data-target="#myModalBusinessUnit" class="margin-bottom-0" id="add-business-unit-global-button">BusinessUnit</a></li>
                                            <li><a data-toggle="modal" data-target="#myModalCreateLogbook" class="margin-bottom-0 no-margin-padding" id="create-logbook-global-button">Logbook</a></li>
                                        </ul>
                                    </li>
                                }

                                @*<li class="">@await Html.PartialAsync("_LoginPartial")</li>*@
                            </ul>
                        </div>
                        @if (User.IsInRole("Manager"))
                        {
                            <a data-toggle="modal" data-target="#myModalNote" id="add-note-global-button" class="btn btn-default navbar-btn"> + <span>Add Note</span></a>
                        }
                    </div>
                </nav>
            </div>
        </header>

        @RenderBody()

        @*<hr />*@


    </div>

    <script src="/assets/plugins/jquery/jquery.min.js"></script>
    <script src="/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/plugins/smoothscroll/SmoothScroll.min.js"></script>
    <script src="/assets/plugins/waypoints/waypoints.min.js"></script>
    <script src="/assets/plugins/counter-up/jquery.counterup.min.js"></script>
    <script src="/assets/plugins/datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/assets/plugins/selectbox/jquery.selectbox-0.1.3.min.js"></script>
    <script src="/assets/plugins/owl-carousel/owl.carousel.min.js"></script>
    <script src="/assets/plugins/isotope/isotope.min.js"></script>
    <script src="/assets/plugins/fancybox/jquery.fancybox.min.js"></script>
    <script src="/assets/plugins/isotope/isotope-triger.min.js"></script>
    <script src="/assets/plugins/rateyo/jquery.rateyo.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDU79W1lu5f6PIiuMqNfT1C6M0e_lq1ECY"></script>
    <script src="/assets/plugins/map/js/rich-marker.js"></script>
    <script src="/assets/plugins/map/js/infobox_packed.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="/assets/js/map.js"></script>
    <script src="/assets/js/app.js"></script>
    <script src="/assets/js/custom.js"></script>
    <script src="/assets/js/business-unit.js"></script>
    <script src="/assets/js/note.js"></script>
    <script src="/assets/js/logbook.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
        <script src="magnific-popup/jquery.magnific-popup.js"></script>*@
    @*<script src="/assets/js/jquery.magnific-popup.min.js"></script>*@
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>


    @await Html.PartialAsync("_ValidationScriptsPartial")


    @RenderSection("Scripts", required: false)
</body>
</html>

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_RemoveManagerModalPartial.cshtml
@model LogbookViewModel
<!-- Remove Manager From Logbook Modal -->
<div class="modal fade" id="myModalRemoveManager" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Choose manager to remove from logbook</h4>
            </div>
            <div class="modal-body">
                <div asp-validation-summary="All" class="text-danger-custom"></div>
                <form id="submit-form-remove-manager" asp-area="Admin" asp-controller="Logbooks" asp-action="RemoveManagerFromLogbook" method="post" class="loginForm">
                    <select id="manager-selector-remove" class="form-control" asp-for="ManagerId"></select>
                    <input type="hidden" id="logbook-id-remove" value="@Model.Id">
                    <div class="margin-5">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Remove Manager From Logbook Modal -->

ManagerLogbook/ManagerLogbook.Web/Views/Shared/_UpdateLogbookModalPartial.cshtml
@model LogbookViewModel
<!--  Start Modal Update Logbook-->
<div class="modal fade" id="myModalUpdateLogbook" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Update a logbook</h4>
            </div>
            <div class="modal-body">
                <div class="text-danger-custom"></div>
                <form id="update-logbook" asp-area="Admin" asp-controller="Logbooks" asp-action="Update" enctype="multipart/form-data" method="post" class="loginForm">
                    <input type="hidden" id="update-logbook-id" value="@Model.Id">
                    <div class="form-group">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <input asp-for="Name" class="form-control" id="name" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger-custom"></span>
                    </div>
                    <select id="business-unit-update-selector" class="form-control" asp-for="BusinessUnitId"></select>
                    <div class="text-centered">
                        <img id="ImgPreview-update-logbook" class="preview1" src="" />
                        <input type="button" id="removeImage1-update-logbook" value="x" class="btn-rmv1" />
                    </div>
                    <label name="Picture" class="btn btn-primary-custom browse margin-5">Upload Image</label>
                    <input type="file" id="imag-update-logbook" name="LogbookPicture" class="btn btn-primary file" accept="image/*">
                    <div class="margin-5">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        <div class="margin-5">
                            @{ var referrer = this.Context.Request.Headers["Referer"]; }
                            @if (referrer != default(StringValues))
                            {
                                <a href="@referrer.ToString()">Go Back</a>
                            }
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Update Logbook Modal -->